# Generated by Django 4.2.10 on 2024-02-15 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='name',
            new_name='title',
        ),
    ]
